### ISSUE TITLE
possible cheat db?

### ISSUE THREAD

**Issue by Ninjistix** [valentinvanelslande/citra#326]
is it possible to have cheat db for something like what dolphin has, that detects the game and loads specific cheats for game/version?

**Comment by valentinvanelslande** [comment]
yes, someday I add it

**Comment by Ninjistix** [comment]
i look forward to it.

**Comment by valentinvanelslande** [comment]
detecting the version is possible, but in the folder names of https://github.com/JourneyOver/CTRPF-AR-CHEAT-CODES/tree/master/Cheats the version does not come.

**Comment by Ninjistix** [comment]
i think that db still needs a lot more work to clean it up and organize cheats by ver no. but i spoke to @JourneyOver about it on gbatemp, but he stated he didnt have the time to do that.

**Comment by JourneyOver** [comment]
I mainly just made the repository for the dump from fort42 from before the site broke, I never really planned for much ahead of adding a few codes/games here and there. Yes I do want to clean the repo up a lot more than it currently is because it is pretty messy in it's current state, but as @Ninjistix said I don't really have the time to do such things right now and I can't really say for sure when I will. 

Ontop of not having the time to do it, I really don't know how I want to do it yet either. I do know I want to split up the folders a bit better on region (will be easy) and get rid of junk codes that either zero out to nothingness due to the fact that some of the codes required you to read comments on fort42 to change part of the code to make it work (Pokemon games have a ton of these) or are just spam codes (like what happened with MK7).

For versioning that's going to be a lot harder though due to a lot of cheats not having a version number on them in the first place and possibilities of cheats working on multiple versions and the like, and I don't think anyone wants to sit down and go through every single cheat of every single game on the db to check for these possibilities (same deal with finding cheats that do or do not work as well).

**Comment by valentinvanelslande** [comment]
I tried adding it in #327, but it does not work
I hardcoded that it shows the cheats of Tomodachi Life (EUR), but the json of the list of titles appears.

**Comment by JourneyOver** [comment]
I can't help with that sadly, as I don't do C++ but I'm sure you'll figure it out eventually.

**Comment by valentinvanelslande** [comment]
now cpr was removed, so now it is much more hard to implement a cheat db

**Comment by JourneyOver** [comment]
what's cpr? :o

**Comment by valentinvanelslande** [comment]
@JourneyOver https://github.com/whoshuu/cpr

**Comment by JourneyOver** [comment]
Ah gotcha, thought it was something I did xD
