### ISSUE TITLE
Tomodachi Life - Writing Mii's name crash

### ISSUE THREAD

**Issue by 2ASCII2** [valentinvanelslande/citra#333]
I was going to put a name to my 5th Mii and then, Citra crashed.

Any solution for this?

Edit: IT HAPPENS WHEN PUTTING LYRICS

**Comment by valentinvanelslande** [comment]
Stopped working?

**Comment by 2ASCII2** [comment]
Well, when i was going to put the nameto the Mii and confirm it it says that the Runtime resquested to close the aplication. There's a problem with the software keyboard code.

Also the lyrics is for the songs.

**Comment by valentinvanelslande** [comment]
@2ASCII2 you are putting symbols, the problem is in the official citra code
The only fix is to dump the swkbd applet from your hacked Nintendo 2DS/3DS/3DS XL/New 2DS XL/New 3DS/New 3DS XL (it has to be version 3072 or citra will crash)/Download it with [3DSToolkit-GUI](https://github.com/valentinvanelslande/3DSToolkit-GUI) and use it for that
If you use a dumped swkbd, citra will freeze when you open swkbd if you have already opened 3
